version: '3.9'

services:

  db:
    image: postgres
    container_name: db_rs
    restart: always
    ports:
      - "9501:5432"
    env_file:
      - backend/renderservice/renderservice/.env

  backend:
    build:
      context: .
    container_name: backend_rs
    command: bash -c "
      ./wait-for-psql.sh db
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8080
      "
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    container_name: redis_rs

  celery:
    build:
      context: .
    container_name: celery_rs
    command: celery -A renderservice worker --loglevel=INFO
    depends_on:
      - backend
      - redis
