version: '3.1'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - ./renderservice/renderservice/.env
  backend:
    build:
      context: .
    ports:
      - 8000:8080
    depends_on:
      - db
