version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "8081:5432"
    env_file:
      - ./renderservice/renderservice/.env
  renderservice:
    build:
      context: .
    expose:
      - "8080"
    depends_on:
      - db
