# Generated by Django 4.0.5 on 2022-08-22 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True, verbose_name='Task name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'db_table': 'tasks',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('create', 'CREATE'), ('rendering', 'RENDERING'), ('complete', 'COMPLETE')], default='create', max_length=9, verbose_name='Status name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='mainapp.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'statuses',
                'db_table': 'statuses',
                'ordering': ('-created_at',),
                'get_latest_by': ('created_at',),
            },
        ),
    ]
